### ISSUE TITLE
Unable to chmod temp file

### ISSUE THREAD

**Issue by wilddeuces** [michalklempa/docker-nifi-registry#16]
Hello, 

currently I am trying to deploy NiFi-Registry in OpenShift 4.1 with this Template.
Sadly I am getting this error when starting the container:
`unable to chmod temp file: chmod /opt/nifi-registry/nifi-registry-0.5.0/conf/nifi-registry.properties: operation not permitted`

In forehand I already had to edit the Dockerfile and add `RUN chmod -R 777 ${PROJECT_BASE_DIR}` to have the right permission to execute the start.sh script.

Do you have any Clue?

Thanks in advance,
Andreas

**Comment by wilddeuces** [comment]
Had to edit Dockerfile, start.sh and providers.xml to match OpenShift conditions.

**Comment by michalklempa** [comment]
Is it that normal docker image runs under user nifi and not root? I have added also `-root` variants of image which omit the instructions to drop user privileges at the end of Dockerfile.

You can derive your image from `michalklempa/nifi-registry:0.5.0-01-root` and then add user nifi if you need one (with your UID:GID):
```
FROM michalklempa/nifi-registry:0.5.0-01-root
ARG UID=10007
ARG GID=10007

RUN addgroup -g ${GID} nifi \
    && adduser -s /bin/bash -u ${UID} -G nifi -D nifi \
    && chown -R nifi:nifi ${PROJECT_BASE_DIR}
USER nifi
```
